### ISSUE TITLE
Quality Assurance Framework V2.0

### ISSUE THREAD

**Issue by JavierTeran** [OCHA-DAP/Data-Team#17]
Quality assurance framework. First version can be found here:
https://docs.google.com/document/d/1Akqkzc-9jplHnTQ6nwt3qzSqRS4MldL8kGaqfFfrvDc/edit

**Comment by JavierTeran** [comment]
Revised version of the QAF. Elaborate on the quality of uncurated datasets section.

**Comment by luiscape** [comment]
Excellent. Let me know if you have a link to share. I'll love to read it. :+1:

**Comment by JavierTeran** [comment]
Completed. Submitted to Sarah for review and approval. 
Document and blog can be found here:
https://drive.google.com/?authuser=0#folders/0B4Sjej3U9V6fYzNBVFBNZGFNLW8

**Comment by JavierTeran** [comment]
Thanks so much @rosnfeld for your comments. Much appreciated.

**Comment by JavierTeran** [comment]
Few editorial changes, latest version of the full report can be found here:
https://drive.google.com/?authuser=0#folders/0B4Sjej3U9V6fYzNBVFBNZGFNLW8

The draft blog has been changed to (?)
@luiscape, could you please update the location of the QAF blog? Thanks

**Comment by JavierTeran** [comment]
Hi @luiscape, is this @ochadataproject Sarah's github name?

**Comment by JavierTeran** [comment]
@ochadataproject Hi Sarah, this is the full report and blog for your revision and approval. Thanks:

https://drive.google.com/?authuser=0#folders/0B4Sjej3U9V6fYzNBVFBNZGFNLW8

https://docs.google.com/document/d/1rEJGF0F_lL1X2ZFTYb3AADvtu9f4g9rjvm_6W-F2_Wo/edit

**Comment by ochadataproject** [comment]
yes :)
