### ISSUE TITLE
Create list of indicator codes for the indicators that don't have proper codes.  e.g. "_blah blah blah"

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/Data-Team#21]
There are a bunch of indicators that were given codes by SW and not by us.  These are things like "_Access to electricity".  

The first step to getting these fixed is to give them real indicator codes.   This is not part of our warp coil goals at the moment, so not urgent.

**Comment by JavierTeran** [comment]
Ok, we will create new indicator IDs for those non-numeric ones.

**Comment by takavarasha** [comment]
I have worked on this draft for the 18 indicator types currently affected by this issue. https://docs.google.com/spreadsheets/d/1PuYm30klSEkOu8-ziX_A6iNmJCtR0KxznVQuSDYQfEI/edit#gid=2130434504

**Comment by cjhendrix** [comment]
Almost done with this one.  All that remains is to make the changes to the URLs **and** filenames on CKAN.  I've done the first one and will work more on this later.  But if you guys want to pitch in feel free. I've added a column to Godfrey's [gdoc](https://docs.google.com/spreadsheets/d/1PuYm30klSEkOu8-ziX_A6iNmJCtR0KxznVQuSDYQfEI/edit#gid=2130434504) to indicate who updated the ckan dataset.

Using [this dataset](http://data.hdx.rwlabs.org/dataset/percentage_of_population_with_access_to_electricity) as a model:
1. Edit the XLSX file.
2. Change the indicator type code (two places in the URL) to the new code from the gdoc
3. Change the indicator type code part of the file name text field
4. Click add
5. This will load the preview page (no preview available for XLSX)
6. Click the download link and be sure the file downloads and is the right file (check the indicator code on the Overview tab)
7. Copy the URL
8. Click edit again.  Then choose the CSV file. Note that we have a bug here and the File picker is at the bottom right instead of the top left.
9. Paste the URL again.
10. Change `xlsx` in two places in the URL to `csv`
11. Change the indicator type code part of the file name text field
12. Click add. This will load the preview page (CSV should preview), if not, something in probably wrong in your URL
13. Click edit again.  Then choose the TXT file. Note that we have a bug here and the File picker is at the bottom right instead of the top left.
14. Paste the URL again.
15. Change the file type at two places in the URL:
    - from XLSX to **Readme** in the middle of the URL
    - from XLSX to **txt** at the end
16. delete the '/fromYear/0/toYear/0' portion of the URL (not needed for Readme files)
17. Change the indicator type code part of the file name text field
18. Click add. This will load the preview page (CSV should preview), if not, something in probably wrong in your URL.
19. Return to the dataset and see how it looks.  Check the names and extensions of the files in particular.

**Comment by JavierTeran** [comment]
@takavarasha Can you check if you can close this issue with what you have done? thanks.

**Comment by takavarasha** [comment]
List of indicators was created and the fix suggested by CJ was applied to the indicators.The list and results of the process are documented here: https://docs.google.com/spreadsheets/d/1PuYm30klSEkOu8-ziX_A6iNmJCtR0KxznVQuSDYQfEI/edit#gid=2130434504
