### ISSUE TITLE
Provide a list of indicators that need to be converted from percentage to ratio.

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/Data-Team#22]
See https://github.com/OCHA-DAP/hdx-ckan/issues/61 for details.

**Comment by JavierTeran** [comment]
Hi CJ, this is the list of indicators that need to be rescale to 0 to 1. Please divide the non-null figure by 100.

_% of routine EPI vaccines financed by government
_Access to electricity (% of population)
_Children 1 year old immunized against measles, percentage
_International migrant stock (% of population)
_Internet users per 100 inhabitants
_Population undernourished, percentage
PCH090
PCX100
PSE160
PSE170
PSE210
PSP100
PVE010
PVE040
PVE130
PVN010
PVN050
PVW010
PVW040

**Comment by cjhendrix** [comment]
Thanks Javier.  It's in the product backlog for CPS:

https://github.com/OCHA-DAP/DAP-System/issues/115

---

CJ Hendrix
Technical Lead, Humanitarian Data Exchange
United Nations Office for the Coordination of Humanitarian Affairs
Tel: +41 (0)22 917 2527
Mobile: +41 (0)79 217 3083
Email: hendrix@un.org
Skype: hendrix.cj
www.unocha.org

**Comment by luiscape** [comment]
The issue has been resolved. Closing it.
