### ISSUE TITLE
Identify new indicators from the ReliefWeb data.

### ISSUE THREAD

**Issue by JavierTeran** [OCHA-DAP/Data-Team#23]
Can you check if any of this 'new' indicators are already in CKAN? Sarah believes that some of these are already included. Please let me know, Thanks, Javier

https://docs.google.com/spreadsheet/ccc?key=0AoSjej3U9V6fdE9ieW9XQzNEOERNQUh1eWdEVFhucFE&usp=drive_web#gid=0

**Comment by luiscape** [comment]
@JavierTeran and @takavarasha Can we go over the broader `creating indicators for ReliefWeb` data sometime today? I have sometime during the afternoon and feel that this is an important tasks, re put RW data on HDX. 

By the way, ReliefWeb just released publicly the v1 of their API. Read their blog post here: http://reliefweb.int/blogpost/transforming-humanitarian-data-knowledge-introducing-reliefweb-api

**Comment by JavierTeran** [comment]
I want to finish few things in the morning but after that let's work on it @luiscape

**Comment by JavierTeran** [comment]
Hi @luiscape do you want to look at it at 11 today?

**Comment by luiscape** [comment]
Hi @JavierTeran , I am a little confused with this issue. What is this about again?
