### ISSUE TITLE
Create source-centric collections

### ISSUE THREAD

**Issue by JavierTeran** [OCHA-DAP/Data-Team#25]
Create collections based on organizations: WorldBank, FAOSTATS

**Comment by JavierTeran** [comment]
Thanks CJ, it is my understanding that you will create a scrip for this.

**Comment by cjhendrix** [comment]
Eventually, yes.  It's not in Warp Coil at the moment.   But when we do get to it, what we will need is an example of the output format(s) you want.  You may already realize that this one is more complex than country-centric or indicator-centric because it is 3 dimensional (country, year, indicator).

**Comment by JavierTeran** [comment]
@takavarasha This activity change its priority. We discuss about this issue but please let me know if you want to discuss again. Thanks

**Comment by JavierTeran** [comment]
@takavarasha Please let me know the progress of this issue. Thanks.

**Comment by takavarasha** [comment]
Will begin working on this issue on 29 April

**Comment by takavarasha** [comment]
Will begin working on this issue on 29 April

**Comment by takavarasha** [comment]
This task will involve creating a single workbook containing all the indicators from a single source. Each indicator will be presented in a single worksheet (tab) in the workbook.

**Comment by takavarasha** [comment]
Completed draft source-centric excel workbook template. A set of templates, one in Excel and two in cvs format can be found here: https://drive.google.com/#folders/0B9nZNVHc4TTcX2N0dGRtbmpiOWc

**Comment by luiscape** [comment]
@takavarasha I noticed that Zimbabwe is spelled with only the first letter capitalized on the files above. All other countries seem to be spelled with all caps (e.g. BOLIVIA). Can we change all country names to first-letter-capitalized style?

**Comment by takavarasha** [comment]
I have checked the countries list on CPS and found that there were two
entries for Zimbabwe. I have deleted the other one. This error was carried
over from the CPS testing that was done about a month ago and recorded in
this issue https://github.com/OCHA-DAP/DAP-System/issues/118

**Comment by luiscape** [comment]
@takavarasha @JavierTeran Is this issue solved?

**Comment by takavarasha** [comment]
The draft is ready (see comments above). This issue has since been reclassified to a middle priority to be handled next week.

**Comment by JavierTeran** [comment]
@takavarasha Please let me know what do we need to re-activate this issue.

**Comment by takavarasha** [comment]
Since we have developed a template for the source-centric collections, I think we should reassign this issue to the dev team to implement the reporting in CPS.

**Comment by JavierTeran** [comment]
Thanks @takavarasha Good point. @cjhendrix Could you please help us with this one?
