### ISSUE TITLE
Bring COD/FODs from pilot countries

### ISSUE THREAD

**Issue by JavierTeran** [OCHA-DAP/Data-Team#27]
Obtain COD/FOD data for Colombia, Kenya and Yemen
Select the best indicators (define best as Homogeneous across pilot countries, consistent)
Upload data into HDX repository

**Comment by JavierTeran** [comment]
@takavarasha Please let me know where are you standing with this activity. Thanks,

**Comment by JavierTeran** [comment]
@takavarasha Please an update. Thanks

**Comment by takavarasha** [comment]
Currently working offline on Yemen data. I will be ready to upload this tomorrow.

**Comment by takavarasha** [comment]
Hope to finalise Yemen on 29 April

Regards,
Godfrey Takavarasha

**Comment by JavierTeran** [comment]
Thanks @takavarasha Please let me know when you will update Colombia and Kenya. If you forseen any blocker please let me know. I would like to have 3 countries data ready by Friday May 9. Thanks,

**Comment by JavierTeran** [comment]
@takavarasha Please remind me to discuss the metadata fields before we close this activity

**Comment by takavarasha** [comment]
I do not foresee any problems with the 9 May goal.

**Comment by luiscape** [comment]
@JavierTeran and @takavarasha I have freed up sometime. Let me know if you need support with this task.

**Comment by takavarasha** [comment]
Thanks, I am just finishing off with Colombia now. Some support on this issue once we know how to proceed would be welcome: https://github.com/OCHA-DAP/Data-Team/issues/46

**Comment by takavarasha** [comment]
CODS and FODs for the three pilots countries are now in production.
