### ISSUE TITLE
Bring UNHCR refugee data into HDX repository

### ISSUE THREAD

**Issue by JavierTeran** [OCHA-DAP/Data-Team#28]
Obtain data from popstats.unhcr
Re-organize the data into indicator-centric types
Upload the data into HDX repository

**Comment by luiscape** [comment]
Should we also divide the dataset into a country-based division?

**Comment by luiscape** [comment]
I assume the task is to divide the data using the format that CPS takes ...

**Comment by luiscape** [comment]
I am reassigning this task to me @JavierTeran. Please advise if this isn't the right way to go. 

I started working on the data yesterday. Here are my notes about working with UNHCR data: https://github.com/luiscape/unhcr-data

**Comment by JavierTeran** [comment]
@luiscape Thanks that would be ideal. @ochadataproject I assuming Luis will be fully dedicated to the data team for the 'end-of-may' effort. Please clarify otherwise. Thanks.

**Comment by ochadataproject** [comment]
Except for help with the blogs and the occasional graphic

**Comment by JavierTeran** [comment]
@ochadataproject  :) Thanks.
@luiscape Today we have a chat with Tarek UNHCR at 10.30 to re-define the UNHCR indicators.

**Comment by luiscape** [comment]
@JavierTeran Would you know what is the current status of this issue?

**Comment by JavierTeran** [comment]
@luiscape Closing this issue as you open a new one #48 for this activity.
