### ISSUE TITLE
Data Visualizations with Tableau

### ISSUE THREAD

**Issue by JavierTeran** [OCHA-DAP/Data-Team#31]
Kevin Lynch (Dublin) is working on this based on pre-crisis data

**Comment by luiscape** [comment]
@JavierTeran Any news on this end? I am eager to close the issue for the week. :dart:

**Comment by JavierTeran** [comment]
Thanks for asking. Kevin had a conflict of priorities and we moved our meeting for Monday at 10.

**Comment by luiscape** [comment]
Perfect then. I'll move it back on `waffle` to `In Discussion` then since we are not finishing this task this week -- or maybe we should rephrase the task ...suggestions?

**Comment by JavierTeran** [comment]
No, I guess, we should leave it as in progress. Lets see how Monday looks like and we decide.

**Comment by JavierTeran** [comment]
@luiscape and @ochadataproject Just to let you know that I work on Tableau visuals today with Kevin and due to his workload he will have updates on them in two weeks. He will be also creating some tableau visuals with FTS data

**Comment by ochadataproject** [comment]
Ok who is responsible for tying these on ckan under the related tab?

**Comment by JavierTeran** [comment]
@ochadataproject  I will do that.

**Comment by luiscape** [comment]
@JavierTeran Let me know if you need any help with this issue.

**Comment by luiscape** [comment]
@JavierTeran I've added Dominik's 'web-app' to the 'children_under_five_mortality_rate_per_1000_live_births' dataset in our staging instance. I will come chat tomorrow with you how exactly you would like that to show up. Right not it isn't all that interesting ...

**Comment by JavierTeran** [comment]
@luiscape  Thanks. All visuals from Kevin are here:
http://public.tableausoftware.com/profile/hdx4727#!/

**Comment by JavierTeran** [comment]
@luiscape Dominik work is on issue #32 Please comment on Dominik's work there please.

**Comment by JavierTeran** [comment]
@luiscape Can you give me some text for the tableau front page by Monday morning? Thanks,

**Comment by JavierTeran** [comment]
This issue is completed.
