### ISSUE TITLE
Explore the possibility of doing R + Shiny visualizations within the team.

### ISSUE THREAD

**Issue by JavierTeran** [OCHA-DAP/Data-Team#32]
CKAN data visuals: 
http://test.data.hdx.rwlabs.org/dataset/test-zwe-population-projection-1982-to-present
Visualisation interface: http://rserver410.iao.fraunhofer.de/shiny/shinyHDX/ 
R: http://rserver410.iao.fraunhofer.de/rstudio/

**Comment by luiscape** [comment]
Serban is currently making an assessment of what would be necessary to fully implement R + Shiny. The assessment should be ready sometime this or next week. No set dates were determined.

**Comment by JavierTeran** [comment]
Thanks Luis for the update. Dominik is creating some visuals. I will assign this issue to him.

**Comment by JavierTeran** [comment]
Updating @OCHA-DAP/Data-team on my talk with Dominik. 
This is his new development:
http://rserver410.iao.fraunhofer.de/shiny/shinyHDX2/
and this
http://rserver410.iao.fraunhofer.de/shiny/shinyHDX/
You have now the possibility to paste the link of the data source and a visualisation will appear. 
Possibility to compare different countries/indicators was requested and Dominik will work on it.
Next call is Friday April 18, 2014

**Comment by luiscape** [comment]
@JavierTeran Want to add Dominik as a `collaborator` here in this thread? 

I tried the second link with an URL, but could not make it work ...

**Comment by JavierTeran** [comment]
Sure, @luiscape should I ask him to register at github first?

**Comment by JavierTeran** [comment]
@luiscape Latest Dominik's work can be found here:

http://hdx.iao.fraunhofer.de/?file=PVH140_baseline.xlsx 

As discussed this morming, please contact him and discuss CSS stuff. Thanks,

**Comment by luiscape** [comment]
I believe this issue is done.
