### ISSUE TITLE
Create a dictionary of country names

### ISSUE THREAD

**Issue by luiscape** [OCHA-DAP/Data-Team#38]
Compare the current HDX list with ReliefWeb.

**Comment by JavierTeran** [comment]
We adopted in HDX the 'Standard Country or Area Codes for Statistical Use' provided by the UN statistics division. 
http://unstats.un.org/unsd/methods/m49/m49.htm

Good idea!

**Comment by luiscape** [comment]
I'm closing this issue as it is almost a duplicate of #39
