### ISSUE TITLE
Determine method for using country names and ISO3 codes

### ISSUE THREAD

**Issue by luiscape** [OCHA-DAP/Data-Team#39]
We currently have a few inconsistencies with the way we assign names and country codes. I did a comparison between our terminology and ReliefWeb's and highlighted some differences here: 

https://docs.google.com/spreadsheets/d/1ZzjQY1LLF0SpyG6dU7keAKtDbpRxf4gOeiL-c3Jb0wE/edit#gid=0

To fully solve this issue, I suggest the following method: 
1. Use the official names provided by UNTERM. (A) We have scraped them already and (B) They come in the 6 official UN languages. 
2. Use discretionary "Short Names" according to our needs. We are responsible for determining those names. Our system could benefit from using "Venezuela" instead of "the Bolivarian Republic of Venezuela". 

Once we define that method I'll create an official "dictionary" of names for the project.

**Comment by luiscape** [comment]
@takavarasha Also let me know what you think.

**Comment by JavierTeran** [comment]
Great analysis. Please see my comments on Issue #38. Godfrey already standardized all focus countries in HDX repository. We did only long names but your proposal of short names is great. What you think @takavarasha ?

**Comment by luiscape** [comment]
The method for **official** names using http://unstats.un.org/unsd/methods/m49/m49alpha.htm sounds appropriate. That would be the right thing to do in my opinion. 

As of "Short Names" we could implement that and use whatever we want -- or whatever makes sense. 

Finally, if translation is necessary, I suggest using UNTERM for the other 5 languages that aren't in the http://unstats.un.org/unsd/methods/m49/m49alpha.htm list.

How does that sound?

**Comment by JavierTeran** [comment]
Sounds good to me, @takavarasha do you agree?

**Comment by luiscape** [comment]
@JavierTeran @takavarasha -- Sorry for being pushy on this issue, but I see this as an essential standard to have -- and an easy win. What would be an update on this issue? And what are the tasks that need to be completed?

**Comment by JavierTeran** [comment]
The agreed spelling of countries names (short and long form) will be defined here:
https://docs.google.com/spreadsheet/ccc?key=0AoSjej3U9V6fdHJzcWNreF8tVDNXTlpaeXl3Z3h3WWc&usp=drive_web#gid=15
(column in orange)
Still work in progress, will update it in the following days.

**Comment by luiscape** [comment]
@JavierTeran just checked the Gspreadsheet and it does seem that it needs some work. Let me know if you need help.

**Comment by JavierTeran** [comment]
@luiscape Yes, please can you jump in there when you have a minute. Thanks

**Comment by JavierTeran** [comment]
We decided we will be using UNSD country codes as default in HDX.
