### ISSUE TITLE
Make the links between organization and source

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/Data-Team#4]
At the moment, the CPS data model is set up to store the link between a source (i.e. a database) and an organzation (i.e. the authority that publishes the database).  However, we don't have a way of getting that information from the data team. When we are ready to tackle this (probably after Flux Capacitor), we will need to set up a way for you guys to make those links (either in the CPS Metadata gdoc or in the Data Manager interface).  To be discussed.

**Comment by luiscape** [comment]
This seems to be no longer relevant. Closing.
