### ISSUE TITLE
New indicators SW

### ISSUE THREAD

**Issue by JavierTeran** [OCHA-DAP/Data-Team#41]
New datasets:
https://docs.google.com/spreadsheet/ccc?key=0AoSjej3U9V6fdE9ieW9XQzNEOERNQUh1eWdEVFhucFE&usp=drive_web#gid=0

**Comment by JavierTeran** [comment]
@takavarasha Lets try to finalize this activity before @aidan leave on Wednesday April 16, 2014.

**Comment by takavarasha** [comment]
Have checked and none of the identified indicators are already included. I have added a column to in the google spreadsheet to record this. Also see the notes on the International migrant stock by sex indicator.
https://docs.google.com/spreadsheet/ccc?key=0AoSjej3U9V6fdE9ieW9XQzNEOERNQUh1eWdEVFhucFE&usp=drive_web#gid=0

**Comment by JavierTeran** [comment]
Thanks @takavarasha. 
@amcguire62, This is the list with new indicators from same sources where ScraperWiki currently extracts data. Please advice.

**Comment by luiscape** [comment]
@JavierTeran What would be the follow-up of this issue?

**Comment by JavierTeran** [comment]
There is some work to be done on CPS. Define indicator types, complete the metadata, and define the validation rules. At the moment @takavarasha is currently working on it.

**Comment by luiscape** [comment]
@JavierTeran Would you know the status of this task?

**Comment by takavarasha** [comment]
Scrapperwiki are fixing the scrappers. The last update from @amcguire62 at the end of Wednesday was that Dragon will look at the issue as soon as he was finished with something else he is was working on.

**Comment by scraperdragon** [comment]
Current status:
- mostly done
- investigating issues with _anc45(SEX=MALE) etc.
- TT021/TT022 and TT023 are new scrapers which look moderately complicated and may take some time.
  Specifically, we may need to automate this using remote-controlled browsers due to the heavy use of javascript and session cookies.
- TT027 looks straightforward.

**Comment by JavierTeran** [comment]
This issue is completed.
