### ISSUE TITLE
Create indicator and collect data from the ReliefWeb 'source' entity. 

### ISSUE THREAD

**Issue by luiscape** [OCHA-DAP/Data-Team#42]
The `source` ReliefWeb entity hasn't been collected. A work-around needs to be found to collect the data from the reliefWeb API.

**Comment by JavierTeran** [comment]
@luiscape Waiting time for response from Shuchi April 30. Otherwise we change the priority to medium. Thanks.

**Comment by luiscape** [comment]
Perfect. Thanks.

**Comment by JavierTeran** [comment]
@luiscape We are closing this issue as the 'Source' indicator does not make any sense.

**Comment by luiscape** [comment]
Perfect. I'll take it out of the CPS-output for tomorrow's meeting.
