### ISSUE TITLE
Performance / Analyitics

### ISSUE THREAD

**Issue by amcguire62** [OCHA-DAP/Data-Team#43]
Can we (via google analytics) capture that activity between ckan and cps (either as downloads or as calls so that if we have a performance issue we can identify / correlate this to performance of the platform #Luis you may already be planning to catch this.

**Comment by davidmegginson** [comment]
This isn't the only option, but one trick with Analytics is adding a bit of Javascript to an outbound link; then Analytics can count all clicks on that link, even if they lead outside the domain:

https://support.google.com/analytics/answer/1136920?hl=en

We'd have two major steps to implement this:
1. @luiscape sets up our Analytics account to track the outbound click events.
2. Someone on the CKAN team makes a very small edit in the template files to add the Javascript to the outbound link element (HTML _a_).

**Comment by luiscape** [comment]
@davidmegginson Analytics tracking could be the same used in our website. 

It seems that the folks at OKFN have developed a neat CKAN extension to do this: http://docs.ckan.org/en/tracking-fixes/tracking.html

Will it be worth exploring it?

**Comment by davidmegginson** [comment]
Definitely.  Do you have a sandbox where you could try it out?  If not, we
could try it at ckan.megginson.com (I'm happy to let you add the site to
your analytics account).

Cheers, David

**Comment by luiscape** [comment]
@davidmegginson If you don't mind, let's give it a try on your sandbox instance. I've just sent you an email with the Google Analytics tracking number and also have given you admin access to our GA account. (Serban is also an admin.) Please change anything as you need. 

Let me know if you need anything else.

**Comment by luiscape** [comment]
@all -- Should I reassign this? What are the next steps to close this issue?

**Comment by davidmegginson** [comment]
Hi, @luiscape — I think it might be most useful if the CKAN devs try this in one of their sandboxes, then in test.data.hdx.rwlabs.org — what do you think, @cjhendrix? If you'd prefer that I do it in ckan.megginson.com first, I can free up an hour to try it out.

**Comment by luiscape** [comment]
@davidmegginson I'll leave that decision to @cjhendrix -- what do you think CJ?

**Comment by cjhendrix** [comment]
Since this seems to be mostly a ckan issue, I'm going to close this one and we'll continue the discussion here: https://github.com/OCHA-DAP/hdx-ckan/issues/196
