### ISSUE TITLE
Create the link between source and organization for all sources in the CPS

### ISSUE THREAD

**Issue by takavarasha** [OCHA-DAP/Data-Team#45]
Resolving this issue will involve editing each source and selecting the correct organization from the Organization drop-down for the source.

**Comment by luiscape** [comment]
Sorry, closed by accident.

**Comment by JavierTeran** [comment]
@takavarasha please let me know if you can close this issue today? thanks

**Comment by takavarasha** [comment]
Created the links between source and organizations. Please see http://manage.hdx.rwlabs.org/hdx/admin/curated/sources/

**Comment by JavierTeran** [comment]
Fantastic @takavarasha  thanks!
