### ISSUE TITLE
Manually fix the indicator metadata for data series on CPS

### ISSUE THREAD

**Issue by takavarasha** [OCHA-DAP/Data-Team#46]
Resolving this issue involves carrying out the following tasks for each data series defined in the CPS at [CPS->Curated Data>Data series].
- Move the text in the [Dataset summary] tab to the Methodology tab.
- Append the text from the [More info] tab to the end of the text in the [Methodology tab].
- Shorten the text in the [Dataset summary] to about one or two lines max

**Comment by takavarasha** [comment]
Will wait for reimportation of this data from the CPS Metadata Management worksheet. See https://github.com/OCHA-DAP/DAP-System/issues/162

**Comment by luiscape** [comment]
@takavarasha as discussed today, I'll finish ReliefWeb, UNHCR, and adding the related tab. If I manage to finish early I'll jump in into this issue.

**Comment by takavarasha** [comment]
Thanks @JavierTeran and @luiscape for helping out. I have finished doing the ones that were left. Metadata for all data series on CPS have been checked. See also https://github.com/OCHA-DAP/Data-Team/issues/52 and https://github.com/OCHA-DAP/Data-Team/issues/53 for issues discovered during the exercise.
