### ISSUE TITLE
Do Quality Assurance for UNHCR data. 

### ISSUE THREAD

**Issue by luiscape** [OCHA-DAP/Data-Team#48]
Re-update the file and create metadata using CPS.

**Comment by luiscape** [comment]
@JavierTeran I am having trouble finding the UNHCR data. Would you point me to where it is please?

**Comment by JavierTeran** [comment]
@luiscape Forwarding email from @davidmegginson  with a zip file now.

**Comment by luiscape** [comment]
@JavierTeran and @davidmegginson you can find the UNHCR dataset here: http://data.hdx.rwlabs.org/dataset/unhcr-refugee-population-statistics

It shows up as "draft" in the instance because I can't add a dataset to any country on prod. (Reportedly this was an issue already fixed in stag.) The data is **in** the system already. So hopefully with an update from stag to prod the dataset will remain. If it doesn't I'll add it again without issues.

**Comment by JavierTeran** [comment]
Thanks @luiscape Please ensure data remains after new deployment to take place today.  Please notify @cjhendrix in case something disappears.  Thanks,

**Comment by davidmegginson** [comment]
@JavierTeran and @luiscape — what has to happen for us to close this task? Is it Javier's being able to download the data and approving of what he sees?

**Comment by luiscape** [comment]
@davidmegginson We were just talking about it today. I created a few (very few) validation tests ([here](https://github.com/luiscape/hdx-unhcr-validation-tests/)) to the UNHCR data. I basically compare it with the data available in the site http://popstats.unhcr.org. The tests were all successful, however there are differences in the dataset, mostly due to the way the names of the countries change throughout the years. 

Me, @JavierTeran and @takavarasha will be meeting today to discuss QA for all the data. I assume we'll decide to close this issue afterwards .

**Comment by JavierTeran** [comment]
We are satisfied with the data quality. We are closing this issue now. Thanks @luiscape
