### ISSUE TITLE
CPS Export Naming for CKAN

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/Data-Team#51]
Just to be sure we don't miss anything, I have created a matrix for all the info we need for naming/populating the CKAN datasets for RW/FTS/whatever.

I have included the existing SW exports as examples. 

https://docs.google.com/spreadsheets/d/1XEajd51uvhE0Erbco1K5t2SgkLebZvZw6Elr-v-wT1A/edit?usp=sharing

**Comment by JavierTeran** [comment]
Done.

**Comment by JavierTeran** [comment]
thanks @cjhendrix 
This issue is completed. Unless we want to use this template for any new data series.
