### ISSUE TITLE
Create random, fake dataset for frog team to play around with. 

### ISSUE THREAD

**Issue by luiscape** [OCHA-DAP/Data-Team#54]
Create a random dataset that uses the model specified by the Common Humanitarian Dataset. @JavierTeran I would like your input here.

**Comment by enw** [comment]
Thx in advance for this. CSV, Excel, JSON doesn't really matter.  We'll just transform it into whatever we need (probably JSON).  It would be nice to have a few different (but perhaps related) datasets - things to compare, analyze, chart.

**Comment by JavierTeran** [comment]
Ok @luiscape @enw I think the best for this would be to have the zip file from SW together with the FTS data, UNHCR data and RW data. This is a big file, CSV but probably the best for you to play around. What do you think @luiscape ?

**Comment by enw** [comment]
@JavierTeran that works for us. Allows us to select subsets of the data to chart/graph/analyze. Actually.... can you filter on Yemen, Syria data. And I think there's a third country that HDX wants to consider for the initial release - Ukraine?

**Comment by luiscape** [comment]
@enw and @JavierTeran Here you can find the data suggested by Javier above: https://github.com/luiscape/data-for-frog/tree/master/frog-data

On [that repository](https://github.com/luiscape/data-for-frog) you can also find detailed comments about the data there. Let me know if you have any questions. 

Note that some of the indicators are working-level indicators. That is, the data is good for development and demonstration purposes, but not anything else. :-)

**Comment by luiscape** [comment]
Hi @enw . I just filtered the data for our three focus countries (Colombia, Yemen, and Kenya). I added some explanatory notes in the [README file](https://github.com/luiscape/data-for-frog), but let me know if you still have any questions. 

I'll be closing this issue now. :-)
