### ISSUE TITLE
What dates to use for country-centric datasets on CKAN?

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/Data-Team#55]
CPS only produced min/max dates by indicator, not by country.  For now we can leave these date ranges blank.  

**Options:**
1. Define a set of default dates for all countriy datasets (though the defaults could be different between baseline, RW, FTS)
2. Build a function in CPS to calculate the min-max based on a country query and output that as a csv (as we did for indicator-centric metadata)
3. Do nothing.  Is it really that critical for these datasets?

**Comment by JavierTeran** [comment]
@cjhendrix That is correct. For the indicator-centric the use of min/max for date of dataset is very meaningful, that tells you for each indicator what is the minimum year with data and what is the latest year with data. The country-centric is a combination of several indicators and probably an average date of dataset may not provide much information. I suggest to leave it blank at the moment.

**Comment by cjhendrix** [comment]
Thanks.  Closing.
