### ISSUE TITLE
Manually added datasets for Yemen, Colombia, Kenya aren't associated with a ckan country

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/Data-Team#56]
This is was probably because that functionality wasn't working in the first release on prod?  It is working now so those changes can be made. 

This could be a good group exercise during the training.  You would have to make everyone a member of the right organization, then ask them to edit the datasets to add the country (and any other metadata they know!)

**Comment by luiscape** [comment]
@cjhendrix and @JavierTeran Should I add the proper datasets to the right countries? I did it for [Kenya](http://data.hdx.rwlabs.org/api/action/group_show?id=ken) before reading this issue . . . :/

**Comment by cjhendrix** [comment]
Based on our conversation just now, I think Javier would prefer it to be 
done and not use it in the training.

**Comment by luiscape** [comment]
@cjhendrix and @JavierTeran I just added all datasets that show up in the search / query for each of those countries to their respective countries. Here is the breakdown: 
- Yemen: 20 datasets. 
- Kenya: 27 datasets. 
- Colombia: 19 datasets.

If you want to see how many files each of those countries have, you can take a look at [this stats page](http://data.hdx.rwlabs.org/stats#largest-groups) in the HDX Repo.

Let me know if it is time to close this issue. :-)

**Comment by JavierTeran** [comment]
This activity was completed programmatically by the Dev Team. Thanks.
