### ISSUE TITLE
Clean up CHD folder to avoid confusion

### ISSUE THREAD

**Issue by davidmegginson** [OCHA-DAP/Data-Team#57]
In the [Common Humanitarian Dataset/](https://drive.google.com/?usp=folder#folders/0B-MUg64rB4Y5dU1BejA2aGU5UVk) folder on Google Drive, it's not obvious which documents are the normative specs for the CHD (I'm assuming [CHD Indicators](https://docs.google.com/spreadsheet/ccc?key=0AjNYvYpDh-dadEs0bEV3VXJ4MXRYa0xVR2l1XzhoQmc&usp=sharing) and [CHD Attributes](https://docs.google.com/spreadsheet/ccc?key=0AjNYvYpDh-dadHdoTzJ3RjgtM2NRYTNPV3ZYSUQxMEE&usp=sharing), but that's just a guess).

I recommend two steps to avoid any confusion/miscommunication in the HDX team:
1. Move all files _except_ those that are official and up-to-date to the [Common Humanitarian Dataset/Old versions/](https://drive.google.com/#folders/0B-MUg64rB4Y5c243Vm9iNGhQOWs) subfolder, so that when someone goes to the [Common Humanitarian Dataset/](https://drive.google.com/?usp=folder#folders/0B-MUg64rB4Y5dU1BejA2aGU5UVk) folder, she'll see only the current specs.
2. Add "[Obsolete]" or something similar to the title of every CHD-like file that's _not_ the official CHD, so that someone seeing them in search results knows what not to use.

(@luiscape — please feel free to reassign to someone else if it makes sense. I don't want to do this myself without help, because I haven't been the one maintaining the CHD over the past couple of months, and I don't want to archive the wrong documents)

**Comment by luiscape** [comment]
Hi @davidmegginson I agree with you on organizing that folder. Let me confirm with Sarah and @JavierTeran what are the most important documents there and start organizing. I'll add updates to this thread.

**Comment by JavierTeran** [comment]
Thanks @davidmegginson and @luiscape 
The latest work on CHD is on 2014 Common humanitarian data set. Please do not move any other data file. Thanks
