### ISSUE TITLE
GINI data looks funny

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/Data-Team#58]
I know nothing about GINI, so maybe this is normal, but the data looks very spotty compared to what I would expect from an economic indicator like this.  

http://test-data.hdx.rwlabs.org/dataset/gini_index

**Comment by luiscape** [comment]
The GINI index is remarkably spotty: http://data.worldbank.org/indicator/SI.POV.GINI

**Comment by cjhendrix** [comment]
Ok, So not our problem.  Thanks for checking. Closing.

**Comment by JavierTeran** [comment]
@cjhendrix Thanks for bring this to us!
