### ISSUE TITLE
Create list of data sources and clarify workflow

### ISSUE THREAD

**Issue by luiscape** [OCHA-DAP/Data-Team#59]
We are currently experiencing an inflow of data in HDX. Our list of data sources remains very informal. It would be great to create a list of data source so we can monitor progress in analyzing how valuable that data is, getting the data, and putting it in our system.

**Comment by JavierTeran** [comment]
@luiscape Is this a duplication of issue #60?
If not, can we join them together?

**Comment by luiscape** [comment]
@JavierTeran I believe this list is part of the workflow in issue #60. I'll merge them = close this one and add the discussion to the other one..
