### ISSUE TITLE
Operational Data: CODHES

### ISSUE THREAD

**Issue by JavierTeran** [OCHA-DAP/Data-Team#61]
Bring CODHES into HDX. 
Contact point Paola Hurtado

**Comment by takavarasha** [comment]
So far, two datasets were uploaded today (2014/06/26). The datasets are:
http://data.hdx.rwlabs.org/dataset/municipal-statistics-of-forced-displacement
http://data.hdx.rwlabs.org/dataset/national-statistics-of-internal-displacement

We expect a third dataset containing more indicators. The data is still being prepared. I will follow up on this one on Friday.

**Comment by takavarasha** [comment]
Spoke to CODHES and third dataset from CODHES expected on Friday 11 July.

**Comment by luiscape** [comment]
Closing this issue: completed. 

PS: This seems to be an interesting candidate for a visualization.
