### ISSUE TITLE
CPS importer updates

### ISSUE THREAD

**Issue by JavierTeran** [OCHA-DAP/Data-Team#62]
Work with Sam to configure importing data from scrapers to HDX.

**Comment by takavarasha** [comment]
Configured the importers for the 48 indicators on production. Currently testing if the configuration worked for all indicators.

**Comment by takavarasha** [comment]
Worked with @seustachi to get the importer working. Will need a few more tests before I close this one

**Comment by luiscape** [comment]
@takavarasha does it mean that the importer is working on staging? I would love to try with the data from UNHCR.

**Comment by takavarasha** [comment]
It worked on staging but came out with a bug on production

**Comment by luiscape** [comment]
@takavarasha Any updates on this one?

**Comment by takavarasha** [comment]
@seustachi fixed the issue with the importer.

**Comment by luiscape** [comment]
@takavarasha Have you had a chance to actually test it?
