### ISSUE TITLE
WFP VAM data in CPS

### ISSUE THREAD

**Issue by JavierTeran** [OCHA-DAP/Data-Team#63]
1. Identify indicators (in progress)
2. Provide country-centric and indicator-centric samples
   https://docs.google.com/file/d/0B4Sjej3U9V6fcmVOajA3OU9zWVE/edit
   https://docs.google.com/file/d/0B4Sjej3U9V6fRW0yRS1TMVhTWnM/edit
3. Create importers @seustachi

**Comment by takavarasha** [comment]
I have uploaded the pcode list for col,yem and ken in this csv file in the Datateam/WFP folder:
https://docs.google.com/file/d/0B9nZNVHc4TTcREdqX1oyeE83Z28

**Comment by luiscape** [comment]
Excellent Godfrey! Really good news! I think this is step 1 of having sub-national entities in CPS. Let's check-in with Sam tomorrow if we can have a bulk-upload of sorts for entities. That would make the process super quick.

**Comment by JavierTeran** [comment]
@takavarasha Thanks for this!

**Comment by luiscape** [comment]
Closing as the task is complete.
