### ISSUE TITLE
Country-specific data: SIDIH in HDX

### ISSUE THREAD

**Issue by JavierTeran** [OCHA-DAP/Data-Team#64]
@luiscape If you could update where you stand on this activity I will be grateful.

**Comment by luiscape** [comment]
Hi Javier, I've split this issue into two different issues for easier tracking: 
- [Bring the SIDIH database to HDX](https://github.com/OCHA-DAP/Data-Team/issues/71)
- [Bring the Monitor database to HDX](https://github.com/OCHA-DAP/Data-Team/issues/72)
