### ISSUE TITLE
New Common Humanitarian Dataset

### ISSUE THREAD

**Issue by JavierTeran** [OCHA-DAP/Data-Team#65]
1. New list of indicators can be found here:
   https://docs.google.com/spreadsheet/ccc?key=0AtnZNVHc4TTcdGdxZEJucFhnOHFzYXMwR1g3eXVSemc&usp=drive_web#gid=4
2. We are working on a new CHD coding system
3. Once it is approved by Management we will implement it with the help/guidance of @davidmegginson

**Comment by luiscape** [comment]
@JavierTeran and @takavarasha I believe we have reached a stable place with the new CHD coding scheme. The latest version is available here ([v.2.1](https://docs.google.com/file/d/0BzNYvYpDh-daNUVZdy1HOU4wakk/edit)). 

Also, we have mapped the old codes to the new codes in this Google Spreadsheet: https://docs.google.com/spreadsheet/ccc?key=0AtnZNVHc4TTcdGdxZEJucFhnOHFzYXMwR1g3eXVSemc&usp=drive_web#gid=12

Please note that new indicators -- UNHCR indicators -- only have the new codes as they were created using the new coding scheme.

Should I close this issue?

**Comment by luiscape** [comment]
In consideration of the new codes, etc. I am closing this task.
