### ISSUE TITLE
Create indicators for UNHCR Data

### ISSUE THREAD

**Issue by luiscape** [OCHA-DAP/Data-Team#69]
Here are the indicators created in this first batch: 
- Refugees per Country of Origin
- Refugees per Country of Destination
- Asylum Seekers per Country of Origin
- Asylum Seekers per Country of Destination
- Others of Concern per Country of Origin
- Others of Concern per Country of Destination
- Returned IDPs per Country of Origin- People of Concern per Country of Origin
- People of Concern per Country of Destination
- Stateless per Country of Origin
- Stateless per Country of Destination

Plus this calculation, that is, an indicator that is calculated by us: 
- People of Concern per Country of Origin
- People of Concern per Country of Destination

There are **14** in total.

**Comment by JavierTeran** [comment]
Hi @luiscape If you go to pop.stats you have this list:

Refugees
Asylum seekers
Returned refugees
Internally displaced persons
Returned IDPs
Stateless persons
Others of concern

We have already refugees. If you could do Asylum seekers, Returned refugees
 and Internally displaced persons for Berlin. I would be grateful.

**Comment by luiscape** [comment]
@JavierTeran We don't have `refugees` in CPS. We have it in the repository, but not in CPS. I thought this task was to standardize the indicators into the CPS format.

**Comment by JavierTeran** [comment]
Thanks @luiscape For the time being, we will do this ad-hoc arrangement to bring data in CKAN as you did for Refugees data. Please let me know if you can try to fit it in CPS otherwise. Just keep in mind we need Asylum seekers, Returned refugees and IDPs for Berlin.

**Comment by luiscape** [comment]
- People of Concern per Country of Origin (CHD.B.PRO.0001.T6)
- People of Concern per Country of Destination (CHD.B.PRO.0002.T6)

Have been created. @takavarasha please let me know if those codes make sense when you have a chance.

@JavierTeran we tried to do a dry-run of adding new indicators to CPS using the data above and it failed due to a bug in CPS. The bug has been reported. In the meantime I'll be working to finish the other indicators from UNHCR and put all their data in the Repo + CPS.

**Comment by luiscape** [comment]
UNHCR just updated its database to include numbers from 2013: http://popstats.unhcr.org/PSQ_TMS.aspx I'll adapt the code to include those data.

**Comment by luiscape** [comment]
I just finished generating indicators in the CPS format. It includes data from 2000 until 2013. Here is the repository for the work: https://github.com/luiscape/unhcr-data

And here is the final data: https://github.com/luiscape/unhcr-data/tree/master/data/cps

The file was uploaded manually to HDX Repo and it is available [here](http://test-data.hdx.rwlabs.org/dataset/raw-unhcr-popstats). We can use that repository to detect the resource automatically on CPS and import the new indicators. 

Here is the list of **16**.

| name | indID | units |
| --- | --- | --- |
| Number of People of Concern by Country of Origin | CHD.B.PRO.0001.T6 | People |
| Number of People of Concern by Country of Residence | CHD.B.PRO.0002.T6 | People |
| Internally displaced by Country of Residence | CHD.B.PRO.0003.T6 | People |
| Internally displaced by Country of Origin | CHD.B.PRO.0004.T6 | People |
| Returned IDPs by Country of Origin | CHD.B.PRO.0005.T6 | People |
| Returned IDPs by Country of Residence | CHD.B.PRO.0006.T6 | People |
| Others of concern by Country of Origin | CHD.B.PRO.0007.T6 | People |
| Others of concern by Country of Residence | CHD.B.PRO.0008.T6 | People |
| Returned refugees by Country of Origin | CHD.B.PRO.0009.T6 | People |
| Returned refugees by Country of Residence | CHD.B.PRO.0010.T6 | People |
| Asylum seekers by Country of Origin | CHD.B.PRO.0011.T6 | People |
| Asylum seekers by Country of Residence | CHD.B.PRO.0012.T6 | People |
| Refugees by Country of Residence | CHD.B.PRO.0013.T6 | People |
| Refugees by Country of Origin | CHD.B.PRO.0014.T6 | People |
| Stateless by Country of Residence | CHD.B.PRO.0015.T6 | People |
| Stateless by Country of Origin | CHD.B.PRO.0016.T6 | People |

I will be closing this issue shortly.

**Comment by takavarasha** [comment]
Codes make sense except for the fact that the one of them is likely to be a
0001

**Comment by luiscape** [comment]
@takavarasha the indicators were extracted from the UNHCR's popstats database. But we still have to codify them using the new coding system. Here you have the current version: https://github.com/luiscape/unhcr-data/tree/master/data/cps

I'll give it a try and post here the results. I would really like to upload that data to CPS tomorrow if time allows.

**Comment by takavarasha** [comment]
Lets upload these at 9am

**Comment by luiscape** [comment]
I just changed the codes based on the updated coding scheme. Here is the new list: 

| name | indID | units |
| --- | --- | --- |
| Number of People of Concern by Country of Origin | CHD.O.PRO.01.T6 | People |
| Number of People of Concern by Country of Residence | CHD.O.PRO.02.T6 | People |
| Internally displaced by Country of Residence | CHD.O.PRO.03.T6 | People |
| Internally displaced by Country of Origin | CHD.O.PRO.03.T6 | People |
| Returned IDPs by Country of Origin | CHD.O.PRO.05.T6 | People |
| Returned IDPs by Country of Residence | CHD.O.PRO.06.T6 | People |
| Others of concern by Country of Origin | CHD.O.PRO.07.T6 | People |
| Others of concern by Country of Residence | CHD.O.PRO.08.T6 | People |
| Returned refugees by Country of Origin | CHD.O.PRO.09.T6 | People |
| Returned refugees by Country of Residence | CHD.O.PRO.10.T6 | People |
| Asylum seekers by Country of Origin | CHD.O.PRO.11.T6 | People |
| Asylum seekers by Country of Residence | CHD.O.PRO.12.T6 | People |
| Refugees by Country of Residence | CHD.O.PRO.13.T6 | People |
| Refugees by Country of Origin | CHD.O.PRO.14.T6 | People |
| Stateless by Country of Residence | CHD.O.PRO.15.T6 | People |
| Stateless by Country of Origin | CHD.O.PRO.16.T6 | People |
| Total Number of People of Concern | CHD.O.PRO.17.T6 | People |

I added those to the protection area of the current CHD list. 

I am closing this issue and creating a new one: #74 

The data can be found [here](https://github.com/luiscape/unhcr-data).

**Comment by JavierTeran** [comment]
When are we going to see the data in CKAN? @luiscape

**Comment by luiscape** [comment]
The data is available in this dataset: http://data.hdx.rwlabs.org/dataset/unhcr-refugee-pop-stats

Those don't have the indicator codes as the indicator codes are for data in CPS only. 

Closing ...
