### ISSUE TITLE
Update indicator codes in the CHD list to add both the T (time-reference) and correct topic-based index numbers

### ISSUE THREAD

**Issue by luiscape** [OCHA-DAP/Data-Team#73]
We have to re-create the codes based on topic (re-create the index) and also add the time-reference (T) to each one of them. This is the latest version of the coding scheme for reference: https://docs.google.com/file/d/0BzNYvYpDh-daNUVZdy1HOU4wakk/edit

**Comment by luiscape** [comment]
This task has been completed.

**Comment by cjhendrix** [comment]
Are these the codes in CPS now?  We are about to add the indicator type codes to the CKAN URLs (and package_extras).

**Comment by cjhendrix** [comment]
Actually, I see that it isn't in CPS, and we will need to coordinate it (since CKAN uses the codes for the API calls).

**Comment by luiscape** [comment]
New codes have been mapped, but haven't been implemented in CPS yet.

**Comment by cjhendrix** [comment]
tagging @alexandru-m-g and @danmihaila so they are aware.
