### ISSUE TITLE
Add the source to the beginning of the description of a dataset on CKAN

### ISSUE THREAD

**Issue by takavarasha** [OCHA-DAP/Data-Team#75]
@ochadataproject would like the source of a dataset to be visible from the search results page. To do this, we have to prefix the source of the dataset to the the description of the dataset. For instance, a dataset whose description is "The number of bananas eaten per year" and whose source is "Banana Authority", should have its description updated to:
"[Source: Banana Authority] The number of bananas eaten per year"

**Comment by takavarasha** [comment]
I have written a script to prefix the descriptions of each dataset. I have tested the script on staging and will close this issue when the script is run on production.

**Comment by luiscape** [comment]
@takavarasha Will you have to run the script again? Or is this issue closed?

**Comment by takavarasha** [comment]
Ran script to effect this change.
