### ISSUE TITLE
Country names

### ISSUE THREAD

**Issue by JavierTeran** [OCHA-DAP/Data-Team#8]

**Comment by JavierTeran** [comment]
Please use http://unstats.un.org/unsd/methods/m49/m49chang.htm

**Comment by takavarasha** [comment]
I have gone through the list of the 73 focus countries in the CPS Metadata Management and found 7 country names that were different from the ones used by UNSTATS. I corrected the names of the 7 countries as follows:

Changed [Bolivia] to [Bolivia (Plurinational State of)]
Changed [Congo, The DRC] to  [Democratic Republic of the Congo]
Changed [Cote D'Ivoire]  to  [Côte d'Ivoire]
Changed [Korea, D.P.R.O.]  to [Democratic People's Republic of Korea]
Changed [Laos] to [Lao People's Democratic Republic]
Changed [Myanmar (Burma) ] to [Myanmar]
Changed [Tanzania, United Republic of] to [United Republic of Tanzania]

During the process, I added 2 new columns the the CPS Metadata Management. The first to store the country names before editing and the second to highlight the rows that were edited.

**Comment by cjhendrix** [comment]
thanks for going through them, Godfrey.    

Do be careful about changing the _structure_ of the spreadsheets, as they are used to generate SQL to bootstrap our databases.  If you feel like you want to change the structure, let me know so we can coordinate it with the dev team.  Changing values is fine with a couple of exceptions; that's what we built it for!

**Comment by takavarasha** [comment]
Thanks CJ. Well noted about changing the structure of the worksheets!

**Comment by JavierTeran** [comment]
Thanks Godfrey.
