### ISSUE TITLE
Sort the data in the Number of Refugees by country data so that the most recent data comes first

### ISSUE THREAD

**Issue by takavarasha** [OCHA-DAP/Data-Team#84]
Sort the data in the CSV files for the following datasets so that the most recent data comes at the top of the list. The affected datasets are:

[Number of Refugees from Colombia](https://data.hdx.rwlabs.org/dataset/number-of-refugees-from-colombia)
[Number of Refugees from Kenya](https://data.hdx.rwlabs.org/dataset/number-of-refugees-from-kenya)
[Number of Refugees from Yemen](https://data.hdx.rwlabs.org/dataset/number-of-refugees-from-yemen)

**Comment by luiscape** [comment]
I just sorted the files. Now the latest year comes on top. Closing issue. 
- https://data.hdx.rwlabs.org/dataset/number-of-refugees-from-colombia/resource/a232bf4f-e982-4b7a-84df-c975796fe5c4
- https://data.hdx.rwlabs.org/dataset/number-of-refugees-from-kenya/resource/148144fc-b7b5-4ff5-bf9f-c8fd6ddf0b99
- https://data.hdx.rwlabs.org/dataset/number-of-refugees-from-yemen/resource/0506628e-9301-451e-9645-79dc1006f634
