### ISSUE TITLE
Formal Names seem to be short names

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/Data-Team#85]
I was looking at https://data.hdx.rwlabs.org/dataset/formal_name/resource/e4a2d3c4-cf78-4eaa-960d-f163950059fd

and noticed that some of the names are not the formal name (Bolivia, for example, should be Bolivia, Plurinational State of).  

Not sure if this is a problem in the data or just a different source than what we used to generate the names.

**Comment by luiscape** [comment]
Also, not sure if I should create a new issue, but the country names are in all caps. Is that intentional?

**Comment by takavarasha** [comment]
This dataset has been deleted from CKAN. Closing this issue.
