### ISSUE TITLE
Problem with geodata endpoints

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/Data-Team#97]
The two non-csv resources in this dataset are not working (either from HDX or directly pasted into the browser).  

https://data.hdx.rwlabs.org/dataset/safe-and-dignified-burial-teams

**Comment by luiscape** [comment]
Hi there CJ, both files seemed to work for me. Here's how they look like in (both SHP and GeoJSON):

![screen shot 2015-01-22 at 9 20 57 am](https://cloud.githubusercontent.com/assets/953118/5857236/16673b10-a218-11e4-8a2b-9f94a38d1a92.png)

Maybe the ArcGIS server they are using had a hickup?!

As per above, I'm closing this issue.

**Comment by cjhendrix** [comment]
Yes, working now!
